apiVersion: apps/v1
kind: Deployment
metadata:
  name: failure-prediction-daemon
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-scaling-ml-daemon
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-routing-optimizer
spec:
  replicas: 3