apiVersion: v1
kind: Namespace
metadata:
  name: aura-ecosystem
  labels:
    name: aura-ecosystem
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-daemons-sa
  namespace: aura-ecosystem
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-daemons-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-daemons-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ml-daemons-role
subjects:
- kind: ServiceAccount
  name: ml-daemons-sa
  namespace: aura-ecosystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-daemons-config
  namespace: aura-ecosystem
data:
  LOG_LEVEL: "info"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.aura-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "aura-ml-daemons"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=aura-ml-daemons,service.version=v2.0.0"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aura-ml-daemons-netpol
  namespace: aura-ecosystem
spec:
  podSelector:
    matchLabels:
      component: ml-daemon
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: aura-ecosystem
    - namespaceSelector:
        matchLabels:
          name: aura-monitoring
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 9090
    - protocol: TCP
      port: 9091
    - protocol: TCP
      port: 9092
    - protocol: TCP
      port: 50051
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: aura-ecosystem
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: aura-monitoring
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 9090
    - protocol: TCP
      port: 4317